# 1. Application settings
server:
  port: 12345
  servlet:
    session:

      timeout: 1800s
  tomcat:
    uri-encoding: UTF-8

spring:
  application:
    name: pollra-server
  thymeleaf:
    mode: HTML
    cache: false

  # 2. Database settings
  datasource:
    jdbcUrl: jdbc:postgresql://110.12.8.172:5432/simpleblog01
    username: pollra
    password: qwer1234
    maximumPoolSize: 10
    auto-commit: true
